# Generated by Django 3.0.1 on 2022-03-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('desc', models.TextField(verbose_name='Description')),
                ('desc_es', models.TextField(default='', verbose_name='Descripcion')),
                ('image', models.ImageField(null=True, upload_to='static/img', verbose_name='Avatar')),
                ('address', models.CharField(max_length=255, verbose_name='Direccion')),
                ('company_type', models.CharField(max_length=255, verbose_name='Company Type')),
                ('company_type_es', models.CharField(default='', max_length=255, verbose_name='Tipo de compania')),
                ('slogan', models.CharField(max_length=255, null=True, verbose_name='Slogan (en)')),
                ('slogan_es', models.CharField(max_length=255, null=True, verbose_name='Slogan (es)')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('map_addres', models.URLField(verbose_name='Direccion google maps, src')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefono')),
            ],
            options={
                'verbose_name_plural': 'A. Entidad',
            },
        ),
    ]
