# Generated by Django 3.0.1 on 2022-03-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VictoryApp', '0002_auto_20220316_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgalery',
            old_name='service',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='productgalery',
            old_name='smallDesc_es',
            new_name='smallDesc',
        ),
    ]
