# Generated by Django 3.0.1 on 2022-03-16 06:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VictoryApp', '0003_auto_20220316_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text_autor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Datos del Autor'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='descripcion_contact',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion de contacto'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image_banner_1',
            field=models.ImageField(upload_to='static/upload', verbose_name='Imagen Banner Inicio'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image_banner_2',
            field=models.ImageField(upload_to='static/upload', verbose_name='Imagen Banner Header'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image_deep',
            field=models.ImageField(upload_to='static/upload', verbose_name='Imagen Fondo Reservar'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image_left',
            field=models.ImageField(upload_to='static/upload', verbose_name='Imagen Izquierda'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image_prefooter',
            field=models.ImageField(upload_to='static/upload', verbose_name='Imagen PreFooter'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image_right',
            field=models.ImageField(upload_to='static/upload', verbose_name='Imagen Derecha'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image_small',
            field=models.ImageField(upload_to='static/upload', verbose_name='Imagen Reservar'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='slogan_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan nivel 1'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='slogan_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan nivel 2'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='slogan_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan nivel 3'),
        ),
    ]
