# Generated by Django 3.0.1 on 2022-03-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VictoryApp', '0004_auto_20220316_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='face',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='entity',
            name='inst',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='entity',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='entity',
            name='twit',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='entity',
            name='yout',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
