# Generated by Django 3.0.1 on 2022-03-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VictoryApp', '0005_auto_20220316_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'D. Categorías'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'C. Productos'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='producto',
            field=models.ManyToManyField(to='VictoryApp.Product', verbose_name='Productos'),
        ),
    ]
