# Generated by Django 3.0.1 on 2022-03-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VictoryApp', '0007_auto_20220317_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/upload', verbose_name='Imagen Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/upload', verbose_name='Imagen Producto'),
        ),
    ]
