# Generated by Django 3.0.1 on 2022-03-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VictoryApp', '0011_auto_20220317_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha de la reservación')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='Telefono')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('cant_persona', models.IntegerField(verbose_name='Cantidad de Personas')),
            ],
            options={
                'verbose_name_plural': 'G. Reservaciones',
            },
        ),
    ]
