# Generated by Django 3.0.1 on 2022-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VictoryApp', '0012_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activado'),
        ),
    ]
