# Generated by Django 3.0.1 on 2022-03-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VictoryApp', '0013_reservation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='fecha_hora',
            field=models.CharField(max_length=255, verbose_name='Fecha de la reservación'),
        ),
    ]
