# Generated by Django 3.0.1 on 2022-03-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VictoryApp', '0014_auto_20220321_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='fecha_hora',
            field=models.DateTimeField(max_length=255, verbose_name='Fecha de la reservación'),
        ),
    ]
